In [67]:
# chargement des librairies
import glob as g
import pandas as pd
import numpy as np
from datetime import datetime
import os

In [68]:
# noms des colonnes dans les fichiers cvs à manipuler
csv_col_names=['Location', 'Date', 'Minimum temperature (°C)', 'Maximum temperature (°C)',
               'Rainfall (mm)', 'Evaporation (mm)', 'Sunshine (hours)',
               'Direction of maximum wind gust ', 'Speed of maximum wind gust (km/h)',
               'Time of maximum wind gust', '9am Temperature (°C)',
               '9am relative humidity (%)', '9am cloud amount (oktas)',
               '9am wind direction', '9am wind speed (km/h)', '9am MSL pressure (hPa)',
               '3pm Temperature (°C)', '3pm relative humidity (%)',
               '3pm cloud amount (oktas)', '3pm wind direction',
               '3pm wind speed (km/h)', '3pm MSL pressure (hPa)']

In [69]:
# chargement du dataset
input_path = "../../datasets/raw/latest/" + "IDCJDW2002.202306.csv"
df = pd.read_csv(input_path, encoding = "ISO-8859-1", names = csv_col_names)
df

,Location,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
0,Daily Weather Observations for Albury-Wodonga ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Prepared at 05:36 UTC on Saturday 17 June 2023...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Copyright 2003 Commonwealth Bureau of Meteorology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Observations from Albury airport.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Some cloud observations are from automated equ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Observations were drawn from Albury Airport AW...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
7,NaN,2023-06-1,8.2,18.6,0.2,NaN,NaN,WNW,26,14:43,...,8,,Calm,1018.7,17.0,69,2,WNW,15,1018.3
8,NaN,2023-06-2,4.8,17.0,0,NaN,NaN,ESE,13,10:15,...,6,NNE,2,1025.5,16.4,73,1,ESE,6,1023.0
9,NaN,2023-06-3,9.2,18.8,0.6,NaN,NaN,SE,20,12:21,...,7,NW,6,1026.2,18.0,69,4,SSE,9,1025.1
10,NaN,2023-06-4,6.0,19.8,0,NaN,NaN,SE,22,15:11,...,NaN,,Calm,1031.9,19.3,57,NaN,SE,9,1028.6
11,NaN,2023-06-5,6.1,17.0,0,NaN,NaN,ENE,37,15:38,...,NaN,,Calm,1028.7,16.3,66,7,ENE,11,1024.8
12,NaN,2023-06-6,9.1,17.5,11.6,NaN,NaN,NNE,33,12:02,...,8,ENE,11,1025.7,16.1,77,7,NNE,20,1023.5
13,NaN,2023-06-7,9.9,19.4,0.4,NaN,NaN,N,50,23:50,...,7,,Calm,1023.8,17.9,81,3,SE,11,1018.8
14,NaN,2023-06-8,13.8,15.9,14.8,NaN,NaN,NNE,59,01:49,...,8,N,24,1010.9,15.3,59,2,NW,20,1012.5
15,NaN,2023-06-9,9.6,14.9,7.4,NaN,NaN,NW,37,06:28,...,8,NW,19,1016.4,13.0,61,8,WNW,19,1016.7
16,NaN,2023-06-10,2.2,14.2,0,NaN,NaN,WSW,19,12:37,...,NaN,,Calm,1025.3,12.8,67,8,SW,11,1023.9
17,NaN,2023-06-11,6.0,15.4,0,NaN,NaN,NNW,15,13:36,...,NaN,NE,7,1026.4,13.7,62,8,SE,6,1022.8
18,NaN,2023-06-12,1.7,11.2,0,NaN,NaN,SE,13,11:32,...,2,,Calm,1021.8,10.8,84,4,SE,9,1018.2
19,NaN,2023-06-13,3.5,14.3,0,NaN,NaN,NW,48,11:03,...,NaN,E,6,1012.9,11.8,84,7,WNW,6,1010.3
20,NaN,2023-06-14,7.5,11.8,8.2,NaN,NaN,WNW,33,03:15,...,8,WNW,13,1015.8,9.5,84,8,WNW,19,1016.6
21,NaN,2023-06-15,5.8,11.8,0,NaN,NaN,WNW,22,12:30,...,8,,Calm,1019.6,11.2,88,8,NNW,9,1017.6
22,NaN,2023-06-16,5.0,16.2,1.0,NaN,NaN,N,24,14:54,...,8,,Calm,1022.9,15.8,63,NaN,N,13,1020.8
23,NaN,2023-06-17,2.0,NaN,0,NaN,NaN,NaN,NaN,NaN,...,NaN,,Calm,1021.2,15.5,54,2,N,19,1016.2

In [75]:
# extraction du code de la localité
text = df["Location"][1]
location_code=text.split(".")[0].split(" ")[-1]
location_code

'IDCJDW2002'

In [76]:
# ajout du code de la localité dans le dataset
df["Location"] = location_code
df

,Location,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
0,IDCJDW2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IDCJDW2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IDCJDW2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IDCJDW2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IDCJDW2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,IDCJDW2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,IDCJDW2002,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
7,IDCJDW2002,2023-06-1,8.2,18.6,0.2,NaN,NaN,WNW,26,14:43,...,8,,Calm,1018.7,17.0,69,2,WNW,15,1018.3
8,IDCJDW2002,2023-06-2,4.8,17.0,0,NaN,NaN,ESE,13,10:15,...,6,NNE,2,1025.5,16.4,73,1,ESE,6,1023.0
9,IDCJDW2002,2023-06-3,9.2,18.8,0.6,NaN,NaN,SE,20,12:21,...,7,NW,6,1026.2,18.0,69,4,SSE,9,1025.1
10,IDCJDW2002,2023-06-4,6.0,19.8,0,NaN,NaN,SE,22,15:11,...,NaN,,Calm,1031.9,19.3,57,NaN,SE,9,1028.6
11,IDCJDW2002,2023-06-5,6.1,17.0,0,NaN,NaN,ENE,37,15:38,...,NaN,,Calm,1028.7,16.3,66,7,ENE,11,1024.8
12,IDCJDW2002,2023-06-6,9.1,17.5,11.6,NaN,NaN,NNE,33,12:02,...,8,ENE,11,1025.7,16.1,77,7,NNE,20,1023.5
13,IDCJDW2002,2023-06-7,9.9,19.4,0.4,NaN,NaN,N,50,23:50,...,7,,Calm,1023.8,17.9,81,3,SE,11,1018.8
14,IDCJDW2002,2023-06-8,13.8,15.9,14.8,NaN,NaN,NNE,59,01:49,...,8,N,24,1010.9,15.3,59,2,NW,20,1012.5
15,IDCJDW2002,2023-06-9,9.6,14.9,7.4,NaN,NaN,NW,37,06:28,...,8,NW,19,1016.4,13.0,61,8,WNW,19,1016.7
16,IDCJDW2002,2023-06-10,2.2,14.2,0,NaN,NaN,WSW,19,12:37,...,NaN,,Calm,1025.3,12.8,67,8,SW,11,1023.9
17,IDCJDW2002,2023-06-11,6.0,15.4,0,NaN,NaN,NNW,15,13:36,...,NaN,NE,7,1026.4,13.7,62,8,SE,6,1022.8
18,IDCJDW2002,2023-06-12,1.7,11.2,0,NaN,NaN,SE,13,11:32,...,2,,Calm,1021.8,10.8,84,4,SE,9,1018.2
19,IDCJDW2002,2023-06-13,3.5,14.3,0,NaN,NaN,NW,48,11:03,...,NaN,E,6,1012.9,11.8,84,7,WNW,6,1010.3
20,IDCJDW2002,2023-06-14,7.5,11.8,8.2,NaN,NaN,WNW,33,03:15,...,8,WNW,13,1015.8,9.5,84,8,WNW,19,1016.6
21,IDCJDW2002,2023-06-15,5.8,11.8,0,NaN,NaN,WNW,22,12:30,...,8,,Calm,1019.6,11.2,88,8,NNW,9,1017.6
22,IDCJDW2002,2023-06-16,5.0,16.2,1.0,NaN,NaN,N,24,14:54,...,8,,Calm,1022.9,15.8,63,NaN,N,13,1020.8
23,IDCJDW2002,2023-06-17,2.0,NaN,0,NaN,NaN,NaN,NaN,NaN,...,NaN,,Calm,1021.2,15.5,54,2,N,19,1016.2

In [77]:
# suppression des lignes ayant au plus 2 valeurs non manquantes
df.dropna(thresh=3, axis=0, inplace=True)
df

,Location,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
6,IDCJDW2002,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
7,IDCJDW2002,2023-06-1,8.2,18.6,0.2,NaN,NaN,WNW,26,14:43,...,8,,Calm,1018.7,17.0,69,2,WNW,15,1018.3
8,IDCJDW2002,2023-06-2,4.8,17.0,0,NaN,NaN,ESE,13,10:15,...,6,NNE,2,1025.5,16.4,73,1,ESE,6,1023.0
9,IDCJDW2002,2023-06-3,9.2,18.8,0.6,NaN,NaN,SE,20,12:21,...,7,NW,6,1026.2,18.0,69,4,SSE,9,1025.1
10,IDCJDW2002,2023-06-4,6.0,19.8,0,NaN,NaN,SE,22,15:11,...,NaN,,Calm,1031.9,19.3,57,NaN,SE,9,1028.6
11,IDCJDW2002,2023-06-5,6.1,17.0,0,NaN,NaN,ENE,37,15:38,...,NaN,,Calm,1028.7,16.3,66,7,ENE,11,1024.8
12,IDCJDW2002,2023-06-6,9.1,17.5,11.6,NaN,NaN,NNE,33,12:02,...,8,ENE,11,1025.7,16.1,77,7,NNE,20,1023.5
13,IDCJDW2002,2023-06-7,9.9,19.4,0.4,NaN,NaN,N,50,23:50,...,7,,Calm,1023.8,17.9,81,3,SE,11,1018.8
14,IDCJDW2002,2023-06-8,13.8,15.9,14.8,NaN,NaN,NNE,59,01:49,...,8,N,24,1010.9,15.3,59,2,NW,20,1012.5
15,IDCJDW2002,2023-06-9,9.6,14.9,7.4,NaN,NaN,NW,37,06:28,...,8,NW,19,1016.4,13.0,61,8,WNW,19,1016.7
16,IDCJDW2002,2023-06-10,2.2,14.2,0,NaN,NaN,WSW,19,12:37,...,NaN,,Calm,1025.3,12.8,67,8,SW,11,1023.9
17,IDCJDW2002,2023-06-11,6.0,15.4,0,NaN,NaN,NNW,15,13:36,...,NaN,NE,7,1026.4,13.7,62,8,SE,6,1022.8
18,IDCJDW2002,2023-06-12,1.7,11.2,0,NaN,NaN,SE,13,11:32,...,2,,Calm,1021.8,10.8,84,4,SE,9,1018.2
19,IDCJDW2002,2023-06-13,3.5,14.3,0,NaN,NaN,NW,48,11:03,...,NaN,E,6,1012.9,11.8,84,7,WNW,6,1010.3
20,IDCJDW2002,2023-06-14,7.5,11.8,8.2,NaN,NaN,WNW,33,03:15,...,8,WNW,13,1015.8,9.5,84,8,WNW,19,1016.6
21,IDCJDW2002,2023-06-15,5.8,11.8,0,NaN,NaN,WNW,22,12:30,...,8,,Calm,1019.6,11.2,88,8,NNW,9,1017.6
22,IDCJDW2002,2023-06-16,5.0,16.2,1.0,NaN,NaN,N,24,14:54,...,8,,Calm,1022.9,15.8,63,NaN,N,13,1020.8
23,IDCJDW2002,2023-06-17,2.0,NaN,0,NaN,NaN,NaN,NaN,NaN,...,NaN,,Calm,1021.2,15.5,54,2,N,19,1016.2

In [78]:
# suppression de la première ligne
df.drop(index=df.index[0], axis=0, inplace=True)
df

,Location,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
7,IDCJDW2002,2023-06-1,8.2,18.6,0.2,NaN,NaN,WNW,26,14:43,...,8,,Calm,1018.7,17.0,69,2,WNW,15,1018.3
8,IDCJDW2002,2023-06-2,4.8,17.0,0,NaN,NaN,ESE,13,10:15,...,6,NNE,2,1025.5,16.4,73,1,ESE,6,1023.0
9,IDCJDW2002,2023-06-3,9.2,18.8,0.6,NaN,NaN,SE,20,12:21,...,7,NW,6,1026.2,18.0,69,4,SSE,9,1025.1
10,IDCJDW2002,2023-06-4,6.0,19.8,0,NaN,NaN,SE,22,15:11,...,NaN,,Calm,1031.9,19.3,57,NaN,SE,9,1028.6
11,IDCJDW2002,2023-06-5,6.1,17.0,0,NaN,NaN,ENE,37,15:38,...,NaN,,Calm,1028.7,16.3,66,7,ENE,11,1024.8
12,IDCJDW2002,2023-06-6,9.1,17.5,11.6,NaN,NaN,NNE,33,12:02,...,8,ENE,11,1025.7,16.1,77,7,NNE,20,1023.5
13,IDCJDW2002,2023-06-7,9.9,19.4,0.4,NaN,NaN,N,50,23:50,...,7,,Calm,1023.8,17.9,81,3,SE,11,1018.8
14,IDCJDW2002,2023-06-8,13.8,15.9,14.8,NaN,NaN,NNE,59,01:49,...,8,N,24,1010.9,15.3,59,2,NW,20,1012.5
15,IDCJDW2002,2023-06-9,9.6,14.9,7.4,NaN,NaN,NW,37,06:28,...,8,NW,19,1016.4,13.0,61,8,WNW,19,1016.7
16,IDCJDW2002,2023-06-10,2.2,14.2,0,NaN,NaN,WSW,19,12:37,...,NaN,,Calm,1025.3,12.8,67,8,SW,11,1023.9
17,IDCJDW2002,2023-06-11,6.0,15.4,0,NaN,NaN,NNW,15,13:36,...,NaN,NE,7,1026.4,13.7,62,8,SE,6,1022.8
18,IDCJDW2002,2023-06-12,1.7,11.2,0,NaN,NaN,SE,13,11:32,...,2,,Calm,1021.8,10.8,84,4,SE,9,1018.2
19,IDCJDW2002,2023-06-13,3.5,14.3,0,NaN,NaN,NW,48,11:03,...,NaN,E,6,1012.9,11.8,84,7,WNW,6,1010.3
20,IDCJDW2002,2023-06-14,7.5,11.8,8.2,NaN,NaN,WNW,33,03:15,...,8,WNW,13,1015.8,9.5,84,8,WNW,19,1016.6
21,IDCJDW2002,2023-06-15,5.8,11.8,0,NaN,NaN,WNW,22,12:30,...,8,,Calm,1019.6,11.2,88,8,NNW,9,1017.6
22,IDCJDW2002,2023-06-16,5.0,16.2,1.0,NaN,NaN,N,24,14:54,...,8,,Calm,1022.9,15.8,63,NaN,N,13,1020.8
23,IDCJDW2002,2023-06-17,2.0,NaN,0,NaN,NaN,NaN,NaN,NaN,...,NaN,,Calm,1021.2,15.5,54,2,N,19,1016.2

In [79]:
# description breve du dataset resultant
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 7 to 23
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Location                           17 non-null     object
 1   Date                               17 non-null     object
 2   Minimum temperature (°C)           17 non-null     object
 3   Maximum temperature (°C)           16 non-null     object
 4   Rainfall (mm)                      17 non-null     object
 5   Evaporation (mm)                   0 non-null      object
 6   Sunshine (hours)                   0 non-null      object
 7   Direction of maximum wind gust     16 non-null     object
 8   Speed of maximum wind gust (km/h)  16 non-null     object
 9   Time of maximum wind gust          16 non-null     object
 10  9am Temperature (°C)               17 non-null     object
 11  9am relative humidity (%)          17 non-null     object
 12  9am cloud amount (oktas)           11 non-null     object
 13  9am wind direction                 17 non-null     object
 14  9am wind speed (km/h)              17 non-null     object
 15  9am MSL pressure (hPa)             17 non-null     object
 16  3pm Temperature (°C)               17 non-null     object
 17  3pm relative humidity (%)          17 non-null     object
 18  3pm cloud amount (oktas)           15 non-null     object
 19  3pm wind direction                 17 non-null     object
 20  3pm wind speed (km/h)              17 non-null     object
 21  3pm MSL pressure (hPa)             17 non-null     object
dtypes: object(22)
memory usage: 3.1+ KB

In [98]:
# colonnes des variables numériques
num_cols = ['Minimum temperature (°C)', 'Maximum temperature (°C)', 'Rainfall (mm)', 'Evaporation (mm)', 'Sunshine (hours)',
            'Speed of maximum wind gust (km/h)', '9am Temperature (°C)', '9am relative humidity (%)', '9am cloud amount (oktas)',
            '9am MSL pressure (hPa)', '9am wind speed (km/h)', '3pm Temperature (°C)', '3pm relative humidity (%)', '3pm cloud amount (oktas)',
            '3pm wind speed (km/h)', '3pm MSL pressure (hPa)']

num_cols

['Minimum temperature (°C)',
 'Maximum temperature (°C)',
 'Rainfall (mm)',
 'Evaporation (mm)',
 'Sunshine (hours)',
 'Speed of maximum wind gust (km/h)',
 '9am Temperature (°C)',
 '9am relative humidity (%)',
 '9am cloud amount (oktas)',
 '9am MSL pressure (hPa)',
 '9am wind speed (km/h)',
 '3pm Temperature (°C)',
 '3pm relative humidity (%)',
 '3pm cloud amount (oktas)',
 '3pm wind speed (km/h)',
 '3pm MSL pressure (hPa)']

In [99]:
# changement de la valeur "Calm" par la valeur "1"
df['9am wind speed (km/h)'].replace({"Calm": "1"}, inplace = True)
df['3pm wind speed (km/h)'].replace({"Calm": "1"}, inplace = True)
df

,Location,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa),Year,Month,Day
7,IDCJDW2002,2023-06-01,8.2,18.6,0.2,NaN,NaN,WNW,26.0,14:43,...,1018.7,17.0,69.0,2.0,WNW,15.0,1018.3,2023,6,1
8,IDCJDW2002,2023-06-02,4.8,17.0,0.0,NaN,NaN,ESE,13.0,10:15,...,1025.5,16.4,73.0,1.0,ESE,6.0,1023.0,2023,6,2
9,IDCJDW2002,2023-06-03,9.2,18.8,0.6,NaN,NaN,SE,20.0,12:21,...,1026.2,18.0,69.0,4.0,SSE,9.0,1025.1,2023,6,3
10,IDCJDW2002,2023-06-04,6.0,19.8,0.0,NaN,NaN,SE,22.0,15:11,...,1031.9,19.3,57.0,NaN,SE,9.0,1028.6,2023,6,4
11,IDCJDW2002,2023-06-05,6.1,17.0,0.0,NaN,NaN,ENE,37.0,15:38,...,1028.7,16.3,66.0,7.0,ENE,11.0,1024.8,2023,6,5
12,IDCJDW2002,2023-06-06,9.1,17.5,11.6,NaN,NaN,NNE,33.0,12:02,...,1025.7,16.1,77.0,7.0,NNE,20.0,1023.5,2023,6,6
13,IDCJDW2002,2023-06-07,9.9,19.4,0.4,NaN,NaN,N,50.0,23:50,...,1023.8,17.9,81.0,3.0,SE,11.0,1018.8,2023,6,7
14,IDCJDW2002,2023-06-08,13.8,15.9,14.8,NaN,NaN,NNE,59.0,01:49,...,1010.9,15.3,59.0,2.0,NW,20.0,1012.5,2023,6,8
15,IDCJDW2002,2023-06-09,9.6,14.9,7.4,NaN,NaN,NW,37.0,06:28,...,1016.4,13.0,61.0,8.0,WNW,19.0,1016.7,2023,6,9
16,IDCJDW2002,2023-06-10,2.2,14.2,0.0,NaN,NaN,WSW,19.0,12:37,...,1025.3,12.8,67.0,8.0,SW,11.0,1023.9,2023,6,10
17,IDCJDW2002,2023-06-11,6.0,15.4,0.0,NaN,NaN,NNW,15.0,13:36,...,1026.4,13.7,62.0,8.0,SE,6.0,1022.8,2023,6,11
18,IDCJDW2002,2023-06-12,1.7,11.2,0.0,NaN,NaN,SE,13.0,11:32,...,1021.8,10.8,84.0,4.0,SE,9.0,1018.2,2023,6,12
19,IDCJDW2002,2023-06-13,3.5,14.3,0.0,NaN,NaN,NW,48.0,11:03,...,1012.9,11.8,84.0,7.0,WNW,6.0,1010.3,2023,6,13
20,IDCJDW2002,2023-06-14,7.5,11.8,8.2,NaN,NaN,WNW,33.0,03:15,...,1015.8,9.5,84.0,8.0,WNW,19.0,1016.6,2023,6,14
21,IDCJDW2002,2023-06-15,5.8,11.8,0.0,NaN,NaN,WNW,22.0,12:30,...,1019.6,11.2,88.0,8.0,NNW,9.0,1017.6,2023,6,15
22,IDCJDW2002,2023-06-16,5.0,16.2,1.0,NaN,NaN,N,24.0,14:54,...,1022.9,15.8,63.0,NaN,N,13.0,1020.8,2023,6,16
23,IDCJDW2002,2023-06-17,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,1021.2,15.5,54.0,2.0,N,19.0,1016.2,2023,6,17

In [83]:
#conversion des colonnes de la liste "num_cols" en types numériques
df[num_cols] = df[num_cols].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 7 to 23
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Location                           17 non-null     object
 1   Date                               17 non-null     object
 2   Minimum temperature (°C)           17 non-null     float64
 3   Maximum temperature (°C)           16 non-null     float64
 4   Rainfall (mm)                      17 non-null     float64
 5   Evaporation (mm)                   0 non-null      float64
 6   Sunshine (hours)                   0 non-null      float64
 7   Direction of maximum wind gust     16 non-null     object
 8   Speed of maximum wind gust (km/h)  16 non-null     float64
 9   Time of maximum wind gust          16 non-null     object
 10  9am Temperature (°C)               17 non-null     float64
 11  9am relative humidity (%)          17 non-null     float64
 12  9am cloud amount (oktas)           11 non-null     float64
 13  9am wind direction                 17 non-null     object
 14  9am wind speed (km/h)              17 non-null     object
 15  9am MSL pressure (hPa)             17 non-null     float64
 16  3pm Temperature (°C)               17 non-null     float64
 17  3pm relative humidity (%)          17 non-null     float64
 18  3pm cloud amount (oktas)           15 non-null     float64
 19  3pm wind direction                 17 non-null     object
 20  3pm wind speed (km/h)              17 non-null     float64
 21  3pm MSL pressure (hPa)             17 non-null     float64
dtypes: float64(15), object(7)
memory usage: 3.1+ KB

In [84]:
# conversion de la colonne Date en un object de type datetime
df['Date'] = pd.to_datetime(df['Date'])
# création de nouvelles colonnes reliées à la date
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [85]:
# extraction d'un nouveau dataset n'incluant pas la colonne "Date"
df_2 = df.drop('Date', axis = 1)

In [86]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 7 to 23
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Location                           17 non-null     object
 1   Minimum temperature (°C)           17 non-null     float64
 2   Maximum temperature (°C)           16 non-null     float64
 3   Rainfall (mm)                      17 non-null     float64
 4   Evaporation (mm)                   0 non-null      float64
 5   Sunshine (hours)                   0 non-null      float64
 6   Direction of maximum wind gust     16 non-null     object
 7   Speed of maximum wind gust (km/h)  16 non-null     float64
 8   Time of maximum wind gust          16 non-null     object
 9   9am Temperature (°C)               17 non-null     float64
 10  9am relative humidity (%)          17 non-null     float64
 11  9am cloud amount (oktas)           11 non-null     float64
 12  9am wind direction                 17 non-null     object
 13  9am wind speed (km/h)              17 non-null     object
 14  9am MSL pressure (hPa)             17 non-null     float64
 15  3pm Temperature (°C)               17 non-null     float64
 16  3pm relative humidity (%)          17 non-null     float64
 17  3pm cloud amount (oktas)           15 non-null     float64
 18  3pm wind direction                 17 non-null     object
 19  3pm wind speed (km/h)              17 non-null     float64
 20  3pm MSL pressure (hPa)             17 non-null     float64
 21  Year                               17 non-null     int64
 22  Month                              17 non-null     int64
 23  Day                                17 non-null     int64
dtypes: float64(15), int64(3), object(6)
memory usage: 3.3+ KB

In [87]:
# extraction d'un nouveau dataset n'incluant pas la colonne "Time of maximum wind gust"
df_3 = df_2.drop("Time of maximum wind gust", axis = 1)
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 7 to 23
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Location                           17 non-null     object
 1   Minimum temperature (°C)           17 non-null     float64
 2   Maximum temperature (°C)           16 non-null     float64
 3   Rainfall (mm)                      17 non-null     float64
 4   Evaporation (mm)                   0 non-null      float64
 5   Sunshine (hours)                   0 non-null      float64
 6   Direction of maximum wind gust     16 non-null     object
 7   Speed of maximum wind gust (km/h)  16 non-null     float64
 8   9am Temperature (°C)               17 non-null     float64
 9   9am relative humidity (%)          17 non-null     float64
 10  9am cloud amount (oktas)           11 non-null     float64
 11  9am wind direction                 17 non-null     object
 12  9am wind speed (km/h)              17 non-null     object
 13  9am MSL pressure (hPa)             17 non-null     float64
 14  3pm Temperature (°C)               17 non-null     float64
 15  3pm relative humidity (%)          17 non-null     float64
 16  3pm cloud amount (oktas)           15 non-null     float64
 17  3pm wind direction                 17 non-null     object
 18  3pm wind speed (km/h)              17 non-null     float64
 19  3pm MSL pressure (hPa)             17 non-null     float64
 20  Year                               17 non-null     int64
 21  Month                              17 non-null     int64
 22  Day                                17 non-null     int64
dtypes: float64(15), int64(3), object(5)
memory usage: 3.2+ KB

In [88]:
# creation de la colonne "RainToday"
df_3["RainToday"] = df_3["Rainfall (mm)"] >= 1
# codage de la variable: RainToday
df_3["RainToday"].replace({False:"No", True: "Yes"}, inplace = True)
df_3

,Location,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),9am Temperature (°C),9am relative humidity (%),...,3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa),Year,Month,Day,RainToday
7,IDCJDW2002,8.2,18.6,0.2,NaN,NaN,WNW,26.0,11.7,95.0,...,17.0,69.0,2.0,WNW,15.0,1018.3,2023,6,1,No
8,IDCJDW2002,4.8,17.0,0.0,NaN,NaN,ESE,13.0,9.7,85.0,...,16.4,73.0,1.0,ESE,6.0,1023.0,2023,6,2,No
9,IDCJDW2002,9.2,18.8,0.6,NaN,NaN,SE,20.0,11.8,96.0,...,18.0,69.0,4.0,SSE,9.0,1025.1,2023,6,3,No
10,IDCJDW2002,6.0,19.8,0.0,NaN,NaN,SE,22.0,11.4,88.0,...,19.3,57.0,NaN,SE,9.0,1028.6,2023,6,4,No
11,IDCJDW2002,6.1,17.0,0.0,NaN,NaN,ENE,37.0,9.1,97.0,...,16.3,66.0,7.0,ENE,11.0,1024.8,2023,6,5,No
12,IDCJDW2002,9.1,17.5,11.6,NaN,NaN,NNE,33.0,13.9,87.0,...,16.1,77.0,7.0,NNE,20.0,1023.5,2023,6,6,Yes
13,IDCJDW2002,9.9,19.4,0.4,NaN,NaN,N,50.0,13.8,93.0,...,17.9,81.0,3.0,SE,11.0,1018.8,2023,6,7,No
14,IDCJDW2002,13.8,15.9,14.8,NaN,NaN,NNE,59.0,14.5,93.0,...,15.3,59.0,2.0,NW,20.0,1012.5,2023,6,8,Yes
15,IDCJDW2002,9.6,14.9,7.4,NaN,NaN,NW,37.0,11.3,87.0,...,13.0,61.0,8.0,WNW,19.0,1016.7,2023,6,9,Yes
16,IDCJDW2002,2.2,14.2,0.0,NaN,NaN,WSW,19.0,8.8,93.0,...,12.8,67.0,8.0,SW,11.0,1023.9,2023,6,10,No
17,IDCJDW2002,6.0,15.4,0.0,NaN,NaN,NNW,15.0,10.3,82.0,...,13.7,62.0,8.0,SE,6.0,1022.8,2023,6,11,No
18,IDCJDW2002,1.7,11.2,0.0,NaN,NaN,SE,13.0,6.1,98.0,...,10.8,84.0,4.0,SE,9.0,1018.2,2023,6,12,No
19,IDCJDW2002,3.5,14.3,0.0,NaN,NaN,NW,48.0,9.3,90.0,...,11.8,84.0,7.0,WNW,6.0,1010.3,2023,6,13,No
20,IDCJDW2002,7.5,11.8,8.2,NaN,NaN,WNW,33.0,8.1,91.0,...,9.5,84.0,8.0,WNW,19.0,1016.6,2023,6,14,Yes
21,IDCJDW2002,5.8,11.8,0.0,NaN,NaN,WNW,22.0,9.0,93.0,...,11.2,88.0,8.0,NNW,9.0,1017.6,2023,6,15,No
22,IDCJDW2002,5.0,16.2,1.0,NaN,NaN,N,24.0,9.2,97.0,...,15.8,63.0,NaN,N,13.0,1020.8,2023,6,16,Yes
23,IDCJDW2002,2.0,NaN,0.0,NaN,NaN,NaN,NaN,6.1,99.0,...,15.5,54.0,2.0,N,19.0,1016.2,2023,6,17,No

In [89]:
# creation de la colonne "RainTomorrow"
df_3["RainTomorrow"] = df_3.shift(-1)["RainToday"]
df_3

,Location,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),9am Temperature (°C),9am relative humidity (%),...,3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa),Year,Month,Day,RainToday,RainTomorrow
7,IDCJDW2002,8.2,18.6,0.2,NaN,NaN,WNW,26.0,11.7,95.0,...,69.0,2.0,WNW,15.0,1018.3,2023,6,1,No,No
8,IDCJDW2002,4.8,17.0,0.0,NaN,NaN,ESE,13.0,9.7,85.0,...,73.0,1.0,ESE,6.0,1023.0,2023,6,2,No,No
9,IDCJDW2002,9.2,18.8,0.6,NaN,NaN,SE,20.0,11.8,96.0,...,69.0,4.0,SSE,9.0,1025.1,2023,6,3,No,No
10,IDCJDW2002,6.0,19.8,0.0,NaN,NaN,SE,22.0,11.4,88.0,...,57.0,NaN,SE,9.0,1028.6,2023,6,4,No,No
11,IDCJDW2002,6.1,17.0,0.0,NaN,NaN,ENE,37.0,9.1,97.0,...,66.0,7.0,ENE,11.0,1024.8,2023,6,5,No,Yes
12,IDCJDW2002,9.1,17.5,11.6,NaN,NaN,NNE,33.0,13.9,87.0,...,77.0,7.0,NNE,20.0,1023.5,2023,6,6,Yes,No
13,IDCJDW2002,9.9,19.4,0.4,NaN,NaN,N,50.0,13.8,93.0,...,81.0,3.0,SE,11.0,1018.8,2023,6,7,No,Yes
14,IDCJDW2002,13.8,15.9,14.8,NaN,NaN,NNE,59.0,14.5,93.0,...,59.0,2.0,NW,20.0,1012.5,2023,6,8,Yes,Yes
15,IDCJDW2002,9.6,14.9,7.4,NaN,NaN,NW,37.0,11.3,87.0,...,61.0,8.0,WNW,19.0,1016.7,2023,6,9,Yes,No
16,IDCJDW2002,2.2,14.2,0.0,NaN,NaN,WSW,19.0,8.8,93.0,...,67.0,8.0,SW,11.0,1023.9,2023,6,10,No,No
17,IDCJDW2002,6.0,15.4,0.0,NaN,NaN,NNW,15.0,10.3,82.0,...,62.0,8.0,SE,6.0,1022.8,2023,6,11,No,No
18,IDCJDW2002,1.7,11.2,0.0,NaN,NaN,SE,13.0,6.1,98.0,...,84.0,4.0,SE,9.0,1018.2,2023,6,12,No,No
19,IDCJDW2002,3.5,14.3,0.0,NaN,NaN,NW,48.0,9.3,90.0,...,84.0,7.0,WNW,6.0,1010.3,2023,6,13,No,Yes
20,IDCJDW2002,7.5,11.8,8.2,NaN,NaN,WNW,33.0,8.1,91.0,...,84.0,8.0,WNW,19.0,1016.6,2023,6,14,Yes,No
21,IDCJDW2002,5.8,11.8,0.0,NaN,NaN,WNW,22.0,9.0,93.0,...,88.0,8.0,NNW,9.0,1017.6,2023,6,15,No,Yes
22,IDCJDW2002,5.0,16.2,1.0,NaN,NaN,N,24.0,9.2,97.0,...,63.0,NaN,N,13.0,1020.8,2023,6,16,Yes,No
23,IDCJDW2002,2.0,NaN,0.0,NaN,NaN,NaN,NaN,6.1,99.0,...,54.0,2.0,N,19.0,1016.2,2023,6,17,No,None

In [90]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 7 to 23
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Location                           17 non-null     object
 1   Minimum temperature (°C)           17 non-null     float64
 2   Maximum temperature (°C)           16 non-null     float64
 3   Rainfall (mm)                      17 non-null     float64
 4   Evaporation (mm)                   0 non-null      float64
 5   Sunshine (hours)                   0 non-null      float64
 6   Direction of maximum wind gust     16 non-null     object
 7   Speed of maximum wind gust (km/h)  16 non-null     float64
 8   9am Temperature (°C)               17 non-null     float64
 9   9am relative humidity (%)          17 non-null     float64
 10  9am cloud amount (oktas)           11 non-null     float64
 11  9am wind direction                 17 non-null     object
 12  9am wind speed (km/h)              17 non-null     object
 13  9am MSL pressure (hPa)             17 non-null     float64
 14  3pm Temperature (°C)               17 non-null     float64
 15  3pm relative humidity (%)          17 non-null     float64
 16  3pm cloud amount (oktas)           15 non-null     float64
 17  3pm wind direction                 17 non-null     object
 18  3pm wind speed (km/h)              17 non-null     float64
 19  3pm MSL pressure (hPa)             17 non-null     float64
 20  Year                               17 non-null     int64
 21  Month                              17 non-null     int64
 22  Day                                17 non-null     int64
 23  RainToday                          17 non-null     object
 24  RainTomorrow                       16 non-null     object
dtypes: float64(15), int64(3), object(7)
memory usage: 3.5+ KB

In [91]:
# dictionnaire pour renommer l'ensemble des colonnes
columns_mapper = {"Minimum temperature (°C)": "mintemp",
                  "Maximum temperature (°C)": "maxtemp",
                  "Rainfall (mm)": "rainfall",
                  "Evaporation (mm)": "evaporation",
                  "Sunshine (hours)": "sunshine",
                  "Direction of maximum wind gust ": "windgustdir",
                  "Speed of maximum wind gust (km/h)": "windgustspeed",
                  "9am Temperature (°C)": "temp9am",
                  "9am relative humidity (%)": "humidity9am",
                  "9am cloud amount (oktas)": "cloud9am",
                  "9am wind direction": "winddir9am",
                  "9am wind speed (km/h)": "windspeed9am",
                  "9am MSL pressure (hPa)": "pressure9am",
                  "3pm Temperature (°C)": "temp3pm",
                  "3pm relative humidity (%)": "humidity3pm",
                  "3pm cloud amount (oktas)": "cloud3pm",
                  "3pm wind direction": "winddir3pm",
                  "3pm wind speed (km/h)": "windspeed3pm",
                  "3pm MSL pressure (hPa)": "pressure3pm",
                  "Year": "year",
                  "Month": "month",
                  "Day": "day",
                  "Location": "location",
                  "RainToday": "raintoday",
                  "RainTomorrow": "raintomorrow"                  
                 }


columns_mapper

{'Minimum temperature (°C)': 'mintemp',
 'Maximum temperature (°C)': 'maxtemp',
 'Rainfall (mm)': 'rainfall',
 'Evaporation (mm)': 'evaporation',
 'Sunshine (hours)': 'sunshine',
 'Direction of maximum wind gust ': 'windgustdir',
 'Speed of maximum wind gust (km/h)': 'windgustspeed',
 '9am Temperature (°C)': 'temp9am',
 '9am relative humidity (%)': 'humidity9am',
 '9am cloud amount (oktas)': 'cloud9am',
 '9am wind direction': 'winddir9am',
 '9am wind speed (km/h)': 'windspeed9am',
 '9am MSL pressure (hPa)': 'pressure9am',
 '3pm Temperature (°C)': 'temp3pm',
 '3pm relative humidity (%)': 'humidity3pm',
 '3pm cloud amount (oktas)': 'cloud3pm',
 '3pm wind direction': 'winddir3pm',
 '3pm wind speed (km/h)': 'windspeed3pm',
 '3pm MSL pressure (hPa)': 'pressure3pm',
 'Year': 'year',
 'Month': 'month',
 'Day': 'day',
 'Location': 'location',
 'RainToday': 'raintoday',
 'RainTomorrow': 'raintomorrow'}

In [92]:
# renommer l'ensemble des colonnes dans un nouveau dataset
df_4 = df_3.rename(columns=columns_mapper, inplace=False, errors="raise")
df_4

,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,temp9am,humidity9am,...,humidity3pm,cloud3pm,winddir3pm,windspeed3pm,pressure3pm,year,month,day,raintoday,raintomorrow
7,IDCJDW2002,8.2,18.6,0.2,NaN,NaN,WNW,26.0,11.7,95.0,...,69.0,2.0,WNW,15.0,1018.3,2023,6,1,No,No
8,IDCJDW2002,4.8,17.0,0.0,NaN,NaN,ESE,13.0,9.7,85.0,...,73.0,1.0,ESE,6.0,1023.0,2023,6,2,No,No
9,IDCJDW2002,9.2,18.8,0.6,NaN,NaN,SE,20.0,11.8,96.0,...,69.0,4.0,SSE,9.0,1025.1,2023,6,3,No,No
10,IDCJDW2002,6.0,19.8,0.0,NaN,NaN,SE,22.0,11.4,88.0,...,57.0,NaN,SE,9.0,1028.6,2023,6,4,No,No
11,IDCJDW2002,6.1,17.0,0.0,NaN,NaN,ENE,37.0,9.1,97.0,...,66.0,7.0,ENE,11.0,1024.8,2023,6,5,No,Yes
12,IDCJDW2002,9.1,17.5,11.6,NaN,NaN,NNE,33.0,13.9,87.0,...,77.0,7.0,NNE,20.0,1023.5,2023,6,6,Yes,No
13,IDCJDW2002,9.9,19.4,0.4,NaN,NaN,N,50.0,13.8,93.0,...,81.0,3.0,SE,11.0,1018.8,2023,6,7,No,Yes
14,IDCJDW2002,13.8,15.9,14.8,NaN,NaN,NNE,59.0,14.5,93.0,...,59.0,2.0,NW,20.0,1012.5,2023,6,8,Yes,Yes
15,IDCJDW2002,9.6,14.9,7.4,NaN,NaN,NW,37.0,11.3,87.0,...,61.0,8.0,WNW,19.0,1016.7,2023,6,9,Yes,No
16,IDCJDW2002,2.2,14.2,0.0,NaN,NaN,WSW,19.0,8.8,93.0,...,67.0,8.0,SW,11.0,1023.9,2023,6,10,No,No
17,IDCJDW2002,6.0,15.4,0.0,NaN,NaN,NNW,15.0,10.3,82.0,...,62.0,8.0,SE,6.0,1022.8,2023,6,11,No,No
18,IDCJDW2002,1.7,11.2,0.0,NaN,NaN,SE,13.0,6.1,98.0,...,84.0,4.0,SE,9.0,1018.2,2023,6,12,No,No
19,IDCJDW2002,3.5,14.3,0.0,NaN,NaN,NW,48.0,9.3,90.0,...,84.0,7.0,WNW,6.0,1010.3,2023,6,13,No,Yes
20,IDCJDW2002,7.5,11.8,8.2,NaN,NaN,WNW,33.0,8.1,91.0,...,84.0,8.0,WNW,19.0,1016.6,2023,6,14,Yes,No
21,IDCJDW2002,5.8,11.8,0.0,NaN,NaN,WNW,22.0,9.0,93.0,...,88.0,8.0,NNW,9.0,1017.6,2023,6,15,No,Yes
22,IDCJDW2002,5.0,16.2,1.0,NaN,NaN,N,24.0,9.2,97.0,...,63.0,NaN,N,13.0,1020.8,2023,6,16,Yes,No
23,IDCJDW2002,2.0,NaN,0.0,NaN,NaN,NaN,NaN,6.1,99.0,...,54.0,2.0,N,19.0,1016.2,2023,6,17,No,None

In [93]:
# réordonner les positions des colonnes
columns_order = ["location","mintemp","maxtemp","rainfall","evaporation","sunshine","windgustdir","windgustspeed",
                 "winddir9am","winddir3pm","windspeed9am","windspeed3pm","humidity9am","humidity3pm","pressure9am",
                 "pressure3pm","cloud9am","cloud3pm","temp9am","temp3pm","raintoday","raintomorrow","year","month","day"]

df_4 = df_4.reindex(columns=columns_order)

df_4

,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,winddir3pm,...,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,year,month,day
7,IDCJDW2002,8.2,18.6,0.2,NaN,NaN,WNW,26.0,,WNW,...,1018.3,8.0,2.0,11.7,17.0,No,No,2023,6,1
8,IDCJDW2002,4.8,17.0,0.0,NaN,NaN,ESE,13.0,NNE,ESE,...,1023.0,6.0,1.0,9.7,16.4,No,No,2023,6,2
9,IDCJDW2002,9.2,18.8,0.6,NaN,NaN,SE,20.0,NW,SSE,...,1025.1,7.0,4.0,11.8,18.0,No,No,2023,6,3
10,IDCJDW2002,6.0,19.8,0.0,NaN,NaN,SE,22.0,,SE,...,1028.6,NaN,NaN,11.4,19.3,No,No,2023,6,4
11,IDCJDW2002,6.1,17.0,0.0,NaN,NaN,ENE,37.0,,ENE,...,1024.8,NaN,7.0,9.1,16.3,No,Yes,2023,6,5
12,IDCJDW2002,9.1,17.5,11.6,NaN,NaN,NNE,33.0,ENE,NNE,...,1023.5,8.0,7.0,13.9,16.1,Yes,No,2023,6,6
13,IDCJDW2002,9.9,19.4,0.4,NaN,NaN,N,50.0,,SE,...,1018.8,7.0,3.0,13.8,17.9,No,Yes,2023,6,7
14,IDCJDW2002,13.8,15.9,14.8,NaN,NaN,NNE,59.0,N,NW,...,1012.5,8.0,2.0,14.5,15.3,Yes,Yes,2023,6,8
15,IDCJDW2002,9.6,14.9,7.4,NaN,NaN,NW,37.0,NW,WNW,...,1016.7,8.0,8.0,11.3,13.0,Yes,No,2023,6,9
16,IDCJDW2002,2.2,14.2,0.0,NaN,NaN,WSW,19.0,,SW,...,1023.9,NaN,8.0,8.8,12.8,No,No,2023,6,10
17,IDCJDW2002,6.0,15.4,0.0,NaN,NaN,NNW,15.0,NE,SE,...,1022.8,NaN,8.0,10.3,13.7,No,No,2023,6,11
18,IDCJDW2002,1.7,11.2,0.0,NaN,NaN,SE,13.0,,SE,...,1018.2,2.0,4.0,6.1,10.8,No,No,2023,6,12
19,IDCJDW2002,3.5,14.3,0.0,NaN,NaN,NW,48.0,E,WNW,...,1010.3,NaN,7.0,9.3,11.8,No,Yes,2023,6,13
20,IDCJDW2002,7.5,11.8,8.2,NaN,NaN,WNW,33.0,WNW,WNW,...,1016.6,8.0,8.0,8.1,9.5,Yes,No,2023,6,14
21,IDCJDW2002,5.8,11.8,0.0,NaN,NaN,WNW,22.0,,NNW,...,1017.6,8.0,8.0,9.0,11.2,No,Yes,2023,6,15
22,IDCJDW2002,5.0,16.2,1.0,NaN,NaN,N,24.0,,N,...,1020.8,8.0,NaN,9.2,15.8,Yes,No,2023,6,16
23,IDCJDW2002,2.0,NaN,0.0,NaN,NaN,NaN,NaN,,N,...,1016.2,NaN,2.0,6.1,15.5,No,None,2023,6,17

In [94]:
# dictionnaire pour changer les codes des localités en noms des localités
location_mapper = {"IDCJDW2002": "Albury",
                   "IDCJDW2005": "BadgerysCreek",
                   "IDCJDW2029": "Cobar",
                   "IDCJDW2097": "Newcastle", 
                   "IDCJDW2030": "CoffsHarbour",
                   "IDCJDW2084": "Moree",
                   "IDCJDW2099": "NorahHead",
                   "IDCJDW2100": "NorfolkIsland",
                   "IDCJDW2111": "Penrith",
                   "IDCJDW2119": "Richmond",
                   "IDCJDW2124": "Sydney",
                   "IDCJDW2125": "SydneyAirport",
                   "IDCJDW2139": "WaggaWagga",
                   "IDCJDW2145": "Williamtown", 
                   "IDCJDW2146": "Wollongong",
                   "IDCJDW2801": "Canberra",
                   "IDCJDW2802": "Tuggeranong",
                   "IDCJDW2804": "MountGinini",
                   "IDCJDW3005": "Ballarat",
                   "IDCJDW3008": "Bendigo",
                   "IDCJDW2142": "Sale",
                   "IDCJDW3049": "MelbourneAirport",
                   "IDCJDW3050": "Melbourne",
                   "IDCJDW3051": "Mildura", 
                   "IDCJDW3059": "Nhil",
                   "IDCJDW3068": "Portland",
                   "IDCJDW3079": "Watsonia",
                   "IDCJDW3101": "Dartmoor",
                   "IDCJDW4019": "Brisbane",
                   "IDCJDW4024": "Cairns",
                   "IDCJDW4050": "GoldCoast",
                   "IDCJDW4128": "Townsville",
                   "IDCJDW5081": "Adelaide",
                   "IDCJDW5041": "MountGambier", 
                   "IDCJDW5049": "Nuriootpa",
                   "IDCJDW5072": "Woomera",
                   "IDCJDW6001": "Albany",
                   "IDCJDW2143": "Witchcliffe",
                   "IDCJDW6108": "PearceRAAF",
                   "IDCJDW6110": "PerthAirport",
                   "IDCJDW6111": "Perth",
                   "IDCJDW6119": "SalmonGums",
                   "IDCJDW6138": "Walpole",
                   "IDCJDW7021": "Hobart", 
                   "IDCJDW7025": "Launceston",
                   "IDCJDW8002": "AliceSprings",
                   "IDCJDW8014": "Darwin",
                   "IDCJDW8024": "Katherine",
                   "IDCJDW8056": "Uluru"
                  }

location_mapper

{'IDCJDW2002': 'Albury',
 'IDCJDW2005': 'BadgerysCreek',
 'IDCJDW2029': 'Cobar',
 'IDCJDW2097': 'Newcastle',
 'IDCJDW2030': 'CoffsHarbour',
 'IDCJDW2084': 'Moree',
 'IDCJDW2099': 'NorahHead',
 'IDCJDW2100': 'NorfolkIsland',
 'IDCJDW2111': 'Penrith',
 'IDCJDW2119': 'Richmond',
 'IDCJDW2124': 'Sydney',
 'IDCJDW2125': 'SydneyAirport',
 'IDCJDW2139': 'WaggaWagga',
 'IDCJDW2145': 'Williamtown',
 'IDCJDW2146': 'Wollongong',
 'IDCJDW2801': 'Canberra',
 'IDCJDW2802': 'Tuggeranong',
 'IDCJDW2804': 'MountGinini',
 'IDCJDW3005': 'Ballarat',
 'IDCJDW3008': 'Bendigo',
 'IDCJDW2142': 'Sale',
 'IDCJDW3049': 'MelbourneAirport',
 'IDCJDW3050': 'Melbourne',
 'IDCJDW3051': 'Mildura',
 'IDCJDW3059': 'Nhil',
 'IDCJDW3068': 'Portland',
 'IDCJDW3079': 'Watsonia',
 'IDCJDW3101': 'Dartmoor',
 'IDCJDW4019': 'Brisbane',
 'IDCJDW4024': 'Cairns',
 'IDCJDW4050': 'GoldCoast',
 'IDCJDW4128': 'Townsville',
 'IDCJDW5081': 'Adelaide',
 'IDCJDW5041': 'MountGambier',
 'IDCJDW5049': 'Nuriootpa',
 'IDCJDW5072': 'Woomera',
 'IDCJDW6001': 'Albany',
 'IDCJDW2143': 'Witchcliffe',
 'IDCJDW6108': 'PearceRAAF',
 'IDCJDW6110': 'PerthAirport',
 'IDCJDW6111': 'Perth',
 'IDCJDW6119': 'SalmonGums',
 'IDCJDW6138': 'Walpole',
 'IDCJDW7021': 'Hobart',
 'IDCJDW7025': 'Launceston',
 'IDCJDW8002': 'AliceSprings',
 'IDCJDW8014': 'Darwin',
 'IDCJDW8024': 'Katherine',
 'IDCJDW8056': 'Uluru'}

In [95]:
# changer les codes des localités en noms des localités

df_4["location"].replace(location_mapper, inplace = True)

df_4

,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,winddir3pm,...,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,year,month,day
7,Albury,8.2,18.6,0.2,NaN,NaN,WNW,26.0,,WNW,...,1018.3,8.0,2.0,11.7,17.0,No,No,2023,6,1
8,Albury,4.8,17.0,0.0,NaN,NaN,ESE,13.0,NNE,ESE,...,1023.0,6.0,1.0,9.7,16.4,No,No,2023,6,2
9,Albury,9.2,18.8,0.6,NaN,NaN,SE,20.0,NW,SSE,...,1025.1,7.0,4.0,11.8,18.0,No,No,2023,6,3
10,Albury,6.0,19.8,0.0,NaN,NaN,SE,22.0,,SE,...,1028.6,NaN,NaN,11.4,19.3,No,No,2023,6,4
11,Albury,6.1,17.0,0.0,NaN,NaN,ENE,37.0,,ENE,...,1024.8,NaN,7.0,9.1,16.3,No,Yes,2023,6,5
12,Albury,9.1,17.5,11.6,NaN,NaN,NNE,33.0,ENE,NNE,...,1023.5,8.0,7.0,13.9,16.1,Yes,No,2023,6,6
13,Albury,9.9,19.4,0.4,NaN,NaN,N,50.0,,SE,...,1018.8,7.0,3.0,13.8,17.9,No,Yes,2023,6,7
14,Albury,13.8,15.9,14.8,NaN,NaN,NNE,59.0,N,NW,...,1012.5,8.0,2.0,14.5,15.3,Yes,Yes,2023,6,8
15,Albury,9.6,14.9,7.4,NaN,NaN,NW,37.0,NW,WNW,...,1016.7,8.0,8.0,11.3,13.0,Yes,No,2023,6,9
16,Albury,2.2,14.2,0.0,NaN,NaN,WSW,19.0,,SW,...,1023.9,NaN,8.0,8.8,12.8,No,No,2023,6,10
17,Albury,6.0,15.4,0.0,NaN,NaN,NNW,15.0,NE,SE,...,1022.8,NaN,8.0,10.3,13.7,No,No,2023,6,11
18,Albury,1.7,11.2,0.0,NaN,NaN,SE,13.0,,SE,...,1018.2,2.0,4.0,6.1,10.8,No,No,2023,6,12
19,Albury,3.5,14.3,0.0,NaN,NaN,NW,48.0,E,WNW,...,1010.3,NaN,7.0,9.3,11.8,No,Yes,2023,6,13
20,Albury,7.5,11.8,8.2,NaN,NaN,WNW,33.0,WNW,WNW,...,1016.6,8.0,8.0,8.1,9.5,Yes,No,2023,6,14
21,Albury,5.8,11.8,0.0,NaN,NaN,WNW,22.0,,NNW,...,1017.6,8.0,8.0,9.0,11.2,No,Yes,2023,6,15
22,Albury,5.0,16.2,1.0,NaN,NaN,N,24.0,,N,...,1020.8,8.0,NaN,9.2,15.8,Yes,No,2023,6,16
23,Albury,2.0,NaN,0.0,NaN,NaN,NaN,NaN,,N,...,1016.2,NaN,2.0,6.1,15.5,No,None,2023,6,17

In [96]:
# On note que la variable réponse (raintomorrow) contient une valeur manquante à la date actuelle (dernière ligne du tableau)
# remplacement des valeurs manquantes par la classe la plus représentée
df_4['raintomorrow'].fillna("No", inplace=True)

In [97]:
# sauvegarde du dataset final
#path = '../../datasets/processed/latest/processed-latest-data' + datetime.now().strftime('-%Y-%m-%d-%H-%M-%S') + '.csv'
path = '../../datasets/processed/latest/processed-weather-aus-latest.csv'
df_4.to_csv(path, index = False)